### ISSUE TITLE
NaN

### ISSUE THREAD

**Issue by Martien** [carpiediem/d3-curve-circlecorners#131]
Hi Ryan, I’m using your `d3-curve-circlecorners` with great pleasure, but it generates NaN in some cases, e.g.

> `d3.line().curve(roundedCorners.radius(6))([[-1,-1],[-1,0],[-1,-5]])`

results in:

> `"M-1,-1LNaN,NaNA0,0,0,0,0,NaN,NaNL-1,-5"`

This happens when `y3 < 0`, while `x1 === x2 === x3`.

**Comment by carpiediem** [comment]
Fixed by https://github.com/carpiediem/d3-curve-circlecorners/commit/323c801241a8f2ed704c94d4c9b6998996e8242f

**Comment by Martien** [comment]
thanks! works fine now.
